### ISSUE TITLE
Possible backport to 1.16.X ?

### ISSUE THREAD

**Issue by Dupiter-AU** [TeamMidnightDust/MidnightControls#161]
**Is your feature request related to a problem? Please describe.**
This request is not related specifically to a problem, but I would just like to see some support for 1.16.5 (not asking for lower, that might be much more difficult), like a little bit of a "legacy"/"nostalgic" version for the old version fans.

**Describe the solution you'd like**
A simple backport to Fabric 1.16.X, if possible! :)

**Describe alternatives you've considered**
I tried to use the latest and oldest version of the current mod with 1.16.5 to end up at a version mismatch crash, I tried using LambdaControls, but after using the latest version of MidnightControls, I feel like there are a lot of features that I miss a lot, like toggle crouch and legacy playstation button UI.

**Additional context**
Can't really think of any additional context I could add here... Sorry!

**Comment by eskoONE** [comment]
is there a big difference between 1.16.1 and 1.16.5? id would actually love to see a working version for  1.16.1 because im learning to speedrun and would like to use my steam deck to explore some seeds and do some runs for fun in bed.

i looked around for a controller mod for fabric for 1.16.1 but havent been able to find anything. i assume there is just none?

it still on your radar @Dupiter-AU?

**Comment by Motschen** [comment]
Just use LambdaControls on older versions
